//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinenifyMe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinenifyMe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minecraft:acacia_door
        ///minecraft:acacia_fence
        ///minecraft:acacia_fence_gate
        ///minecraft:acacia_stairs
        ///minecraft:activator_rail
        ///minecraft:air
        ///minecraft:anvil
        ///minecraft:barrier
        ///minecraft:beacon
        ///minecraft:bed
        ///minecraft:bedrock
        ///minecraft:birch_door
        ///minecraft:birch_fence
        ///minecraft:birch_fence_gate
        ///minecraft:birch_stairs
        ///minecraft:bookshelf
        ///minecraft:brewing_stand
        ///minecraft:brick_block
        ///minecraft:brick_stairs
        ///minecraft:brown_mushroom
        ///minecraft:brown_mushroom_block
        ///minecraft:cactus
        ///minecraft:cake
        ///minecraft:carpet
        ///minecr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string blocks {
            get {
                return ResourceManager.GetString("blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlockType {
            get {
                object obj = ResourceManager.GetObject("BlockType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap curveToPoint {
            get {
                object obj = ResourceManager.GetObject("curveToPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap functionGenerator {
            get {
                object obj = ResourceManager.GetObject("functionGenerator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minecraft:acacia_door
        ///minecraft:acacia_fence
        ///minecraft:acacia_fence_gate
        ///minecraft:acacia_stairs
        ///minecraft:activator_rail
        ///minecraft:anvil
        ///minecraft:apple
        ///minecraft:armor_stand
        ///minecraft:arrow
        ///minecraft:baked_potato
        ///minecraft:banner
        ///minecraft:barrier
        ///minecraft:beacon
        ///minecraft:bed
        ///minecraft:bedrock
        ///minecraft:beef
        ///minecraft:birch_door
        ///minecraft:birch_fence
        ///minecraft:birch_fence_gate
        ///minecraft:birch_stairs
        ///minecraft:blaze_powder
        ///minecraft:blaze_rod
        ///minecraft:boat
        ///minecraft:bone
        ///minecraft:book
        ///minecraft:bookshe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap itemType {
            get {
                object obj = ResourceManager.GetObject("itemType", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previewBlocks {
            get {
                object obj = ResourceManager.GetObject("previewBlocks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap surfaceToPoint {
            get {
                object obj = ResourceManager.GetObject("surfaceToPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
